# Background and foreground colors synced with GTK theme
background = #160D16
foreground = #fef9f3

# Standard colors (Matches your GTK palette)
palette = 0=#160D16
palette = 1=#fe4d2a
palette = 2=#83bc7b
palette = 3=#f7f24f
palette = 4=#a7aaaf
palette = 5=#e382d2
palette = 6=#91e3e1
palette = 7=#F6C9A0

# Bright colors (Matches your GTK bright variants)
palette = 8=#4d3c4d
palette = 9=#ff9985
palette = 10=#bbddb6
palette = 11=#fffca3
palette = 12=#d7d8db
palette = 13=#f6cbee
palette = 14=#d9f7f6
palette = 15=#fef9f3